[package]
name = "jan-dns"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41", features = ["full"]}
hickory-resolver = {version = "0.24.1", features = ["tokio-runtime"]}
anyhow = "1"
